services:
  ros2-turtle:
    build: .
    container_name: ros2_turtle
    restart: unless-stopped
    network_mode: host

    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

      # GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_SCALE_FACTOR=3

    volumes:
      - ros2_data:/ros2_ws/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

volumes:
  ros2_data: